# Generated by Django 5.2.17 on 2026-10-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='If set in future, notice stays hidden until this date/time.', null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='published', max_length=10),
        ),
    ]
